### ISSUE TITLE
Panel helper platform?

### ISSUE THREAD

**Issue by km-13c** [Eccenux/panel-helper#1]
I would like to kindly ask you on what platform Panel Helper does open?

**Comment by Eccenux** [comment]
Locally I usually work on WAMP, but remotely I work on LAMP. So basically Apache, MySQL/MariaDB, PHP. Platform understood as a operation system shouldn't matter.

I don't provide installation instructions here, sorry. Every edition of the Polish citizen panels I worked on were a bit different and every one of them required tweaking code and db schema. If you are not into programming you will not be able to really use this project.

**Comment by km-13c** [comment]
Ok. So for now, thank you very much :)
